name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Cache
      uses: Swatinem/rust-cache@v2.8.0
    - name: Check formatting
      run: cargo fmt --verbose --check

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Cache
      uses: Swatinem/rust-cache@v2.8.0
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-all-features
    - name: Check all feature combinations
      run: cargo check-all-features

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Cache
      uses: Swatinem/rust-cache@v2.8.0
    - name: Clippy
      run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Cache
      uses: Swatinem/rust-cache@v2.8.0
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-all-features
    - name: Test all feature combinations
      run: cargo test-all-features
      
  build:
    strategy:
      matrix:
        toolchain: [stable, beta]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
    - name: Cache
      uses: Swatinem/rust-cache@v2.8.0
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-all-features
    - name: Build all feature combinations
      run: cargo build-all-features

  verify_msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Cache
      uses: Swatinem/rust-cache@v2.8.0
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-msrv
    - name: Verify MSRV
      run: cargo msrv verify --all-features
